server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movies-api
          uri: host.docker.internal:movies-api:8091
          predicates:
            - Path=/movies/**
          filters:
            - StripPrefix=2
        - id: users-service
          uri: host.docker.internal:users-service:8092
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=2

    security:
      oauth2:
        client:
          provider:
            keycloak-provider:
              issuer-uri: http://localhost:8082/realms/digitalmedia
              jwk-set-uri: http://localhost:8082/realms/digitalmedia/protocol/openid-connect/certs
          registration:
            api-gateway:
              client-id: api-gateway
              client-secret: zpynKZ5jzVtzzwcP6xYmKYJW5kqHmfsR
              authorization-grant-type: authorization-code
              redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
              scope: openid
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true